import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"

import { AuthProvider } from "./context/AuthContext"
import Logout from "./components/Logout"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <AuthProvider>
          <header className="flex  p-4 bg-blue-500 text-white">
            <div className="flex justify-between items-center max-w-screen-lg w-full mx-auto">
              <span className="font-bold text-2xl">Belvo client</span>
              <Logout />
            </div>
          </header>
          <div className="flex flex-col items-center min-h-screen p-8 pb-20 font-[family-name:var(--font-geist-sans)]">
            <main className="flex flex-col gap-8 row-start-2 max-w-screen-sm w-full">
              {children}
            </main>
          </div>
        </AuthProvider>
      </body>
    </html>
  )
}
